name: Go Test and Coverage

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: Test and Coverage
      run: |
        go test ./... -coverprofile=coverage.txt
        go tool cover -func=coverage.txt
    - name: Plan Terraform
      id: printcoverage
      continue-on-error: true
      run:  cat coverage.txt     
    - name: Comment PR
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          Test Results:
          \``` 
          ${{ steps.printcoverage.outputs.stdout }}
          \```