name: Go Test and Coverage

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: Test and Coverage
      run: |
        go test ./... -coverprofile=coverage.txt
        go tool cover -func=coverage.txt

    - name: generate diff
      run: |
        git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff

    - name: compute new code coverage
      id: covdiffaction
      uses: panagiotisptr/cov-diff@main
      with:
        path: .
        coverprofile: coverage.txt
        diff: pr.diff
        module: github.com/panagiotisptr/cov-diff

    - name: Comment
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          Coverage on new code: ${{ steps.covdiffaction.outputs.covdiff }}%